// GENERATED by tools/build_life_js.py from life_content.py — do not edit.
// Percentages are pre-computed so the result screen and the archetype page
// can never show a different number for the same direction.
var LIFE_LABELS = {
 "strong": "Kuchli taraflaringiz",
 "weak": "Eʼtibor beradigan tomonlaringiz",
 "careers": "Sizga mos kelishi mumkin boʻlgan yoʻnalishlar",
 "disclaimer": "Bu foizlar — sizning ikkita eng kuchli xususiyatingiz shu yoʻnalishga qanchalik mos kelishini koʻrsatadi. Bu bashorat emas: qiziqishingiz, imkoniyatingiz va real tajribangiz undan muhimroq."
};
var LIFE = {
 "A|C": {
  "areas": [
   {
    "strong": [
     [
      "Aytilmasa ham qilish",
      "Uydagi ishni koʻrsangiz, buyruq kutmaysiz."
     ],
     [
      "Vaʼdaga sodiqlik",
      "Kichkina vaʼdani ham unutmaysiz."
     ],
     [
      "Kattalarga gʻamxoʻrlik",
      "Buvi-bobongiz eng koʻp sizga suyanadi."
     ],
     [
      "Uy tartibi",
      "Siz boʻlgan joyda hech narsa yoʻqolmaydi."
     ],
     [
      "Sokin borliq",
      "Baland gapirmasangiz ham, siz yoʻq boʻlsangiz darrov sezilasiz."
     ]
    ],
    "sub": "Uyda va yaqinlaringiz orasida",
    "title": "Oilada",
    "weak": [
     [
      "Hamma yukni olish",
      "Uy ishlarining koʻpi sizda toʻplanib qoladi va siz indamaysiz."
     ],
     [
      "Aybdorlik hissi",
      "Biror ishni qilolmasangiz, oʻzingizni uzoq ayblaysiz."
     ],
     [
      "«Yoʻq» deyolmaslik",
      "Charchagan boʻlsangiz ham rad eta olmaysiz."
     ],
     [
      "Oʻz ehtiyojini oxirgi qoʻyish",
      "Hammaning ishi bitgach, oʻzingizga vaqt qolmaydi."
     ],
     [
      "Maqtovni kutish va kutmaslik",
      "Qilgan ishingiz sezilmasa xafa boʻlasiz, lekin buni aytmaysiz."
     ]
    ]
   },
   {
    "strong": [
     [
      "Ishonib topshiriladi",
      "Sinf pulini yoki muhim hujjatni sizga berishadi."
     ],
     [
      "Muddatni buzmaslik",
      "Topshiriq har doim vaqtida."
     ],
     [
      "Sinfdoshga yordam",
      "Tushuntirib berishdan zerikmaysiz."
     ],
     [
      "Sokin izchillik",
      "Koʻzga tashlanmasangiz ham, natijangiz barqaror."
     ],
     [
      "Jamoada ishonchli boʻgʻin",
      "Sizning qismingiz albatta tayyor boʻladi."
     ]
    ],
    "sub": "Darsda, imtihonda va sinfdoshlar orasida",
    "title": "Maktabda",
    "weak": [
     [
      "Ortiqcha yuk",
      "Guruhning ishini oxirida siz tugatasiz — har safar."
     ],
     [
      "Oʻzini koʻrsatmaslik",
      "Qilgan ishingizni boshqa birov oʻziniki qilib aytsa ham indamaysiz."
     ],
     [
      "Xato qilishdan qoʻrqish",
      "Kimnidir umidsizlikka solishdan qoʻrqasiz va shu sabab tavakkal qilmaysiz."
     ],
     [
      "Savol bermaslik",
      "Vaqt olib qoʻyaman deb tushunmaganingizni soʻramaysiz."
     ],
     [
      "Yetakchilikdan qochish",
      "Sizga ishonishsa ham, boshliqlikni boshqaga berasiz."
     ]
    ]
   },
   {
    "strong": [
     [
      "Tayanch doʻst",
      "Ogʻir kunda birinchi boʻlib sizga qoʻngʻiroq qilishadi."
     ],
     [
      "Sir saqlash",
      "Sizdan hech narsa chiqmaydi."
     ],
     [
      "Eslab qolish",
      "Doʻstingizning imtihon sanasini oʻzidan yaxshiroq bilasiz."
     ],
     [
      "Xolis maslahat",
      "Yoqimli emas, foydali gapni aytasiz — lekin yumshoq."
     ],
     [
      "Uzoq sodiqlik",
      "Doʻstlikni birinchi boʻlib uzmaysiz."
     ]
    ],
    "sub": "Doʻstlik va yaqin munosabatlarda",
    "title": "Munosabatlarda",
    "weak": [
     [
      "Foydalanilish",
      "Yaxshiligingizni bilgan odam undan foydalanadi, siz esa sezmaganga olasiz."
     ],
     [
      "Chegara yoʻqligi",
      "Har qanday vaqtda yordamga tayyorsiz — oʻzingizga zarar boʻlsa ham."
     ],
     [
      "Xafalikni yigʻish",
      "Ranjishlarni ichingizda toʻplaysiz, keyin birdan uzoqlashasiz."
     ],
     [
      "Oʻz muammosini aytmaslik",
      "Doʻstlaringiz sizni doim yaxshi deb oʻylaydi."
     ],
     [
      "Rad eta olmaslik",
      "Toʻgʻri kelmaydigan taklifga ham rozi boʻlasiz."
     ]
    ]
   }
  ],
  "careers": [
   {
    "name": "Hamshiralik va tibbiy yordam",
    "pct": 87,
    "why": "Gʻamxoʻrlik va aniqlik bir vaqtda kerak — ikkalasi ham sizda bor."
   },
   {
    "name": "Buxgalteriya va boshqaruv hisobi",
    "pct": 85,
    "why": "Sinchkovlik va halollik bu ishning asosi."
   },
   {
    "name": "Kutubxona, arxiv, hujjatchilik",
    "pct": 80,
    "why": "Tartib va ishonch talab qilinadigan sokin ish sizga yaqin."
   },
   {
    "name": "Boshlangʻich sinf oʻqituvchisi",
    "pct": 77,
    "why": "Sabr va izchillik — kichik bolalar bilan ishlashning butun mazmuni."
   },
   {
    "name": "Ijtimoiy himoya va gʻamxoʻrlik xizmatlari",
    "pct": 75,
    "why": "Odamga ham, hujjatga ham eʼtiborli boʻlish kerak boʻlgan soha."
   }
  ]
 },
 "ES|A": {
  "areas": [
   {
    "strong": [
     [
      "Uydagi tinchlik",
      "Janjal chiqqanda ovozingizni koʻtarmaysiz. Koʻpincha vaziyatni yumshatadigan birinchi odam aynan siz boʻlasiz."
     ],
     [
      "Sirdosh",
      "Aka-ukangiz yoki opa-singlingiz muammosini birinchi boʻlib sizga aytadi — chunki siz uni kattalarga yetkazmasligingizni biladi."
     ],
     [
      "Soʻralmagan yordam",
      "Kimningdir charchaganini koʻrsangiz, iltimos qilinishini kutmaysiz. Idishlarni yuvib qoʻygan odam odatda siz boʻlasiz."
     ],
     [
      "Kattalar bilan sabr",
      "Buvingiz yoki bobongiz bir voqeani uchinchi marta aytsa ham zerikmay tinglaysiz. Bu koʻpchilikda yoʻq."
     ],
     [
      "Uydagi vaʼda",
      "Oilaga bergan soʻzingizni eslab qolasiz. Kichkina vaʼdani ham unutmaysiz."
     ]
    ],
    "sub": "Uyda va yaqinlaringiz orasida",
    "title": "Oilada",
    "weak": [
     [
      "Oʻz ehtiyojingizni yashirish",
      "«Menga hech narsa kerak emas» deb aytaverib, haqiqatan kerak boʻlganda ham soʻramay qoʻyasiz."
     ],
     [
      "Mavzuni oʻzgartirish",
      "Kelishmovchilikni hal qilish oʻrniga gapni boshqa yoqqa burasiz. Muammo yoʻqolmaydi — yigʻilib boradi."
     ],
     [
      "Hammaning yukini olish",
      "«Menga osonroq» deb uy ishlarini oʻzingiz qilib qoʻyasiz, keyin charchoq sababini tushunmaysiz."
     ],
     [
      "Ranjiganini bildirmaslik",
      "Xafa boʻlganingizda jim boʻlasiz. Oilangiz nega jim boʻlganingizni bilmaydi va sizni tushunmagandek koʻrinadi."
     ],
     [
      "«Yoʻq» deyolmaslik",
      "Oʻz rejangiz buzilsa ham har bir iltimosni bajarasiz. Keyin oʻzingizga vaqt qolmaganidan siqilasiz."
     ]
    ]
   },
   {
    "strong": [
     [
      "Guruh ishida tayanch",
      "Jamoa topshirigʻida hech kim qoʻl urmagan qismni oxirida siz tugatasiz."
     ],
     [
      "Sinfdoshlar ishonchi",
      "Boshqalar bilan til topa olmaydigan oʻquvchi ham sizga ochiladi, chunki siz hukm qilmaysiz."
     ],
     [
      "Imtihonda xotirjamlik",
      "Atrofdagilar hayajonlanganda siz odatdagi tezligingizda ishlaysiz. Bilganingizni unutib qoʻymaysiz."
     ],
     [
      "Oʻqituvchi bilan munosabat",
      "Qarshilik koʻrsatmaysiz va vaʼdangizda turasiz — shuning uchun masʼuliyatli topshiriq koʻpincha sizga beriladi."
     ],
     [
      "Sekin, lekin uzluksiz",
      "Bir kechada emas, har kuni ozgina. Yil oxirida natija shu tarzda toʻplanadi."
     ]
    ],
    "sub": "Darsda, imtihonda va sinfdoshlar orasida",
    "title": "Maktabda",
    "weak": [
     [
      "Savol bermaslik",
      "Tushunmagan joyingizni soʻrashdan tortinasiz — «sinfni ushlab qolaman» deb oʻylaysiz. Keyin oʻsha mavzu qiyinlashib qoladi."
     ],
     [
      "Oʻzini past baholash",
      "Ishingizni sinfdoshingiznikidan yomonroq deb hisoblaysiz. Koʻpincha bu notoʻgʻri boʻladi."
     ],
     [
      "Yetakchilikdan chekinish",
      "Guruh boshligʻi boʻlishni boshqaga berasiz, hatto jamoa sizni tanlagan boʻlsa ham."
     ],
     [
      "Bahsda taslim",
      "Kimdir qatʼiy ohangda gapirsa, toʻgʻri javobingizni ham himoya qilmaysiz."
     ],
     [
      "Yordam oʻrniga bajarib berish",
      "Tushuntirish oʻrniga oʻzingiz qilib qoʻyasiz. Ular oʻrganmaydi, siz esa ikki karra ishlaysiz."
     ]
    ]
   },
   {
    "strong": [
     [
      "Haqiqiy tinglovchi",
      "Javobingizni tayyorlab turmaysiz — chinakam eshitasiz. Buni odamlar darrov sezadi."
     ],
     [
      "Sir sizda qoladi",
      "Sizga aytilgan gap boshqa hech kimga yetib bormaydi. Doʻstlaringiz buni sinab koʻrgan."
     ],
     [
      "Yarashtiruvchi",
      "Ikki doʻstingiz urishib qolsa, ular orasida gaplashadigan odam koʻpincha siz boʻlasiz."
     ],
     [
      "Uzoq doʻstlik",
      "Sizning doʻstligingiz yillar davom etadi. Aloqani birinchi boʻlib uzmaysiz."
     ],
     [
      "Hukm qilmaslik",
      "Xato qilgan odam ham sizga aytishdan qoʻrqmaydi. Shuning uchun sizga aytiladi."
     ]
    ],
    "sub": "Doʻstlik va yaqin munosabatlarda",
    "title": "Munosabatlarda",
    "weak": [
     [
      "Foydalanilib qolish",
      "Yaxshiligingizni bilgan odam undan foydalanishi mumkin — va siz buni koʻpincha oxirgi boʻlib sezasiz."
     ],
     [
      "Chegara yoʻqligi",
      "Yarim tunda ham telefoningiz ochiq. Oʻzingizga dam beradigan vaqt qolmaydi."
     ],
     [
      "Xafalikni yigʻish",
      "Ranjiganingizni aytmay yuraverasiz, keyin birdan uzoqlashasiz. Doʻstingiz sababini tushunmaydi."
     ],
     [
      "Hammaga yoqishga urinish",
      "Oʻz fikringizni aytmay, koʻpchilikning fikriga qoʻshilaverasiz. Sizning fikringiz ham kerak edi."
     ],
     [
      "Oʻzingizga vaqt qoldirmaslik",
      "Doʻstlaringizga shu qadar berilasizki, yolgʻiz qolish sizga aybdek tuyuladi. Aslida dam olish ham kerak."
     ]
    ]
   }
  ],
  "careers": [
   {
    "name": "Psixolog va maslahatchi",
    "pct": 82,
    "why": "Odamlar sizga sirini aytadi, va siz ularning gapini boʻlmay eshitasiz. Bosim ostida xotirjam qolish esa bu ishda majburiy."
   },
   {
    "name": "Ijtimoiy ish va HR",
    "pct": 77,
    "why": "Jamoadagi keskinlikni boshqalardan oldin sezasiz va odamlarni yarashtirasiz. Faqat bu yerda oʻz fikringizni ham aytish kerak boʻladi."
   },
   {
    "name": "Logoped va maxsus pedagogika",
    "pct": 77,
    "why": "Natija oylab koʻrinmaydigan ishda ham taslim boʻlmaysiz. Bu yerda sabr iqtidordan muhimroq."
   },
   {
    "name": "Tibbiyot va hamshiralik",
    "pct": 75,
    "why": "Shoshilinch holat sizni sarosimaga solmaydi va bemorga insoniy munosabatda boʻlasiz. Qatʼiy tartib-qoidaga koʻnikish esa mehnat talab qiladi."
   },
   {
    "name": "Oʻqituvchilik va tarbiya",
    "pct": 70,
    "why": "Tushunmagan bolaga uchinchi marta ham birinchi martadagidek tushuntira olasiz. Lekin sinf oldida ovoz chiqarish siz uchun eng qiyini boʻladi."
   }
  ]
 },
 "ES|C": {
  "areas": [
   {
    "strong": [
     [
      "Vaʼda = bajarilgan ish",
      "Oilangiz sizga eslatmaydi, chunki keragi yoʻq."
     ],
     [
      "Inqirozda xotirjam",
      "Uyda ogʻir vaziyat boʻlsa, siz vahima qilmaysiz."
     ],
     [
      "Uzoqni rejalashtirish",
      "Kelasi yil haqida bugundan gapiradigan odam siz."
     ],
     [
      "Tejamkorlik",
      "Pulni oʻylab sarflaysiz, kichkina yoshdan."
     ],
     [
      "Kichiklarga tayanch",
      "Ukalaringiz darsda qiynalsa sizga keladi."
     ]
    ],
    "sub": "Uyda va yaqinlaringiz orasida",
    "title": "Oilada",
    "weak": [
     [
      "Reja buzilganda",
      "Kutilmagan oʻzgarish sizni boshqalardan koʻra koʻproq bezovta qiladi, tashqaridan bilinmasa ham."
     ],
     [
      "Hissiyotni aytmaslik",
      "Sevgi va tashvishni soʻz bilan emas, ish bilan koʻrsatasiz — oilangiz buni har doim ham tushunmaydi."
     ],
     [
      "Dam olishni kechiktirish",
      "«Avval ish» deb, hech qachon dam olmaysiz."
     ],
     [
      "Qatʼiylik",
      "Bir marta qaror qilgan narsangizni oʻzgartirish qiyin."
     ],
     [
      "Yordam soʻramaslik",
      "Ogʻir boʻlsa ham oʻzingiz koʻtarasiz."
     ]
    ]
   },
   {
    "strong": [
     [
      "Uzoq masofaga chidash",
      "Uch oylik tayyorgarlik sizni qoʻrqitmaydi."
     ],
     [
      "Imtihonda barqaror",
      "Hayajon bilimingizni oʻchirmaydi."
     ],
     [
      "Jadval boʻyicha oʻqish",
      "Har kuni ozgina — va yil oxirida natija koʻrinadi."
     ],
     [
      "Ishonchli jamoadosh",
      "Sizga topshirilgan qism albatta tayyor boʻladi."
     ],
     [
      "Tartibli daftar",
      "Yozganingizni istalgan vaqtda topasiz."
     ]
    ],
    "sub": "Darsda, imtihonda va sinfdoshlar orasida",
    "title": "Maktabda",
    "weak": [
     [
      "Oʻzgarishga qarshilik",
      "Oʻqituvchi usulini oʻzgartirsa, siz qiynalasiz."
     ],
     [
      "Yangilikdan qochish",
      "Sinovdan oʻtgan usulni afzal koʻrib, yangisini sinamaysiz."
     ],
     [
      "Savol bermaslik",
      "Tushunmaganingizni oʻzingiz hal qilishga urinasiz."
     ],
     [
      "Mukammallik bosimi",
      "Toʻrt baho sizni boshqalardan koʻra koʻproq tushkunlikka soladi."
     ],
     [
      "Ijodiy topshiriqda qiyinchilik",
      "«Xohlaganingizni qiling» degan topshiriq sizni chalkashtiradi."
     ]
    ]
   },
   {
    "strong": [
     [
      "Soʻzida turish",
      "Aytgan vaqtingizda kelasiz — har safar."
     ],
     [
      "Sirni saqlash",
      "Sizga aytilgan gap sizda qoladi."
     ],
     [
      "Qiyinchilikda yoningizda",
      "Doʻstingizga ogʻir kunda birinchi boʻlib siz kelasiz."
     ],
     [
      "Uzoq doʻstlik",
      "Bolalikdagi doʻstingiz hali ham doʻstingiz."
     ],
     [
      "Vahimasiz",
      "Doʻstingiz sarosimaga tushganda siz aniq gapirasiz."
     ]
    ],
    "sub": "Doʻstlik va yaqin munosabatlarda",
    "title": "Munosabatlarda",
    "weak": [
     [
      "Rejasizlikdan noqulaylik",
      "«Hozir chiqamizmi?» degan taklif sizni bezovta qiladi."
     ],
     [
      "Doira torligi",
      "Yangi doʻst orttirishga shoshilmaysiz."
     ],
     [
      "Oʻz dardini aytmaslik",
      "Doʻstlaringiz sizning ham qiynalishingizni bilmaydi."
     ],
     [
      "Sovuq koʻrinish",
      "Hissiyotni kam koʻrsatganingiz uchun sizni befarq deb oʻylashadi."
     ],
     [
      "Kechirishga qiyinchilik",
      "Vaʼdasida turmagan odamni uzoq eslab yurasiz."
     ]
    ]
   }
  ],
  "careers": [
   {
    "name": "Muhandislik va qurilish",
    "pct": 87,
    "why": "Uzoq muddatli, aniqlik talab qiladigan ish sizga toʻgʻri keladi."
   },
   {
    "name": "Moliya va buxgalteriya",
    "pct": 85,
    "why": "Diqqat va barqarorlik — bu ishning ikki asosiy talabi."
   },
   {
    "name": "Tibbiyot va jarrohlik",
    "pct": 80,
    "why": "Bosim ostida qoʻlingiz titramaydi va tartibga qatʼiy amal qilasiz."
   },
   {
    "name": "Huquq va notariat",
    "pct": 74,
    "why": "Hujjat bilan sinchkov ishlash sizni zeriktirmaydi."
   },
   {
    "name": "Logistika va ishlab chiqarish",
    "pct": 72,
    "why": "Katta tizimni jadval boʻyicha yuritish sizning maydoningiz."
   }
  ]
 },
 "ES|E": {
  "areas": [
   {
    "strong": [
     [
      "Bosim ostida qaror",
      "Uyda kutilmagan muammo chiqsa, hamma sizga qaraydi — chunki siz sarosimaga tushmaysiz."
     ],
     [
      "Mehmon kutish",
      "Uyga odam kelganda suhbatni siz boshlaysiz va hech kim chetda qolmaydi."
     ],
     [
      "Janjalni toʻxtatish",
      "Ovozingizni koʻtarmay bir gap aytasiz va tortishuv tinadi. Buni oilangiz biladi."
     ],
     [
      "Kichiklarga namuna",
      "Ukalaringiz sizga taqlid qiladi, siz aytmasangiz ham."
     ],
     [
      "Ishonchli yelka",
      "Muhim oilaviy suhbatga sizni ham chaqirishadi, garchi yoshingiz kichik boʻlsa ham."
     ]
    ],
    "sub": "Uyda va yaqinlaringiz orasida",
    "title": "Oilada",
    "weak": [
     [
      "Befarqdek koʻrinish",
      "Xotirjamligingiz «unga farqi yoʻq» degan taassurot qoldiradi. Yaqinlaringiz sizdan koʻproq hissiyot kutadi."
     ],
     [
      "Oʻz tashvishini aytmaslik",
      "Hammaning muammosini eshitasiz, oʻzingiznikini hech kimga aytmaysiz."
     ],
     [
      "Soʻralmasdan boshqarish",
      "Vaziyatni tez oʻz qoʻlingizga olasiz — baʼzan oilangiz shunchaki tinglashingizni kutayotgan boʻladi."
     ],
     [
      "«Sen bardoshlisan» yorligʻi",
      "Sizdan hech kim holingizni soʻramay qoʻyadi, chunki doim yaxshi koʻrinasiz."
     ],
     [
      "Hissiy suhbatdan qochish",
      "Yigʻi va koʻz yosh boʻlgan joyda oʻzingizni noqulay his qilasiz va mavzuni amaliy tomonga burasiz."
     ]
    ]
   },
   {
    "strong": [
     [
      "Sinf oldida gapirish",
      "Taqdimotda ovozingiz titramaydi. Koʻpchilik uchun bu eng qiyin narsa."
     ],
     [
      "Guruh yetakchisi",
      "Jamoa adashib qolganda yoʻnalishni koʻrsatadigan odam siz boʻlasiz."
     ],
     [
      "Imtihonda barqarorlik",
      "Bilganingizni hayajondan unutmaysiz — bu bilimdan kam ahamiyatli emas."
     ],
     [
      "Nizoni hal qilish",
      "Sinfdoshlar urishib qolsa, oʻqituvchi sizni chaqiradi."
     ],
     [
      "Oʻqituvchilar ishonchi",
      "Masʼuliyatli topshiriq koʻpincha sizga beriladi."
     ]
    ],
    "sub": "Darsda, imtihonda va sinfdoshlar orasida",
    "title": "Maktabda",
    "weak": [
     [
      "Guruh ishini oʻzlashtirish",
      "«Tezroq boʻladi» deb hammasini oʻzingiz qilasiz. Jamoa hech narsa oʻrganmaydi."
     ],
     [
      "Yordam soʻramaslik",
      "Tushunmaganingizni tan olish sizga yetakchilikni yoʻqotishdek tuyuladi."
     ],
     [
      "Jim oʻquvchini bosib qoʻyish",
      "Siz gapirganingizda tortinchoq sinfdoshingiz umuman gapirmay qoʻyadi."
     ],
     [
      "Sekin darsda zerikish",
      "Mavzu takrorlanganda eʼtiboringiz soʻnadi va oddiy joyini oʻtkazib yuborasiz."
     ],
     [
      "Xato qilishdan qoʻrqish",
      "Hamma sizga qaraydi degan fikr yangi narsani sinab koʻrishingizga xalaqit beradi."
     ]
    ]
   },
   {
    "strong": [
     [
      "Davra tashkilotchisi",
      "Uchrashuv boʻlishi yoki boʻlmasligi koʻpincha sizga bogʻliq."
     ],
     [
      "Vahimasiz maslahat",
      "Doʻstingiz sarosimaga tushganda siz aniq nima qilishni aytasiz."
     ],
     [
      "Yangi odam bilan oson",
      "Notanish davraga kirib ketish sizga qiyin emas."
     ],
     [
      "Adolatli hakam",
      "Ikki tomonni ham eshitasiz, keyin gapirasiz."
     ],
     [
      "Vaʼdaga sodiq",
      "Kelaman deganingizda kelasiz. Buni doʻstlaringiz sanaydi."
     ]
    ],
    "sub": "Doʻstlik va yaqin munosabatlarda",
    "title": "Munosabatlarda",
    "weak": [
     [
      "Zaifligini koʻrsatmaslik",
      "Doʻstlaringiz sizning ham qiynalishingizni tasavvur qilolmaydi."
     ],
     [
      "Hammani bir masofada tutish",
      "Koʻp odam bilan yaxshimisiz, lekin juda yaqin doʻst kam."
     ],
     [
      "Yordam soʻrash qiyinligi",
      "Doim beruvchi tomon boʻlasiz, olishni bilmaysiz."
     ],
     [
      "Boshqarib yuborish",
      "Doʻstona uchrashuv ham sizning rejangiz boʻyicha oʻtadi — baʼzan boshqalar ham tanlashni xohlaydi."
     ],
     [
      "Hissiy suhbatni qisqartirish",
      "Doʻstingiz dardini aytganda tezda yechim taklif qilasiz, u esa faqat eshitilishini kutgandi."
     ]
    ]
   }
  ],
  "careers": [
   {
    "name": "Boshqaruv va menejment",
    "pct": 87,
    "why": "Bosim ostida qaror qabul qilish va odamlarni ergashtirish — bu ishning kundalik mazmuni. Rejalashtirish tomonini alohida oʻrganishingiz kerak."
   },
   {
    "name": "Diplomatiya va xalqaro munosabatlar",
    "pct": 84,
    "why": "Keskin suhbatni yumshata olasiz va notanish muhitda tez moslashasiz."
   },
   {
    "name": "Huquq va advokatura",
    "pct": 80,
    "why": "Qarshi tomon ovozini koʻtarganda ham siz koʻtarmaysiz. Sud zalida bu ustunlik. Hujjat bilan ishlash esa sabr talab qiladi."
   },
   {
    "name": "Favqulodda xizmat va tibbiyot",
    "pct": 77,
    "why": "Hamma sarosimaga tushganda sizning boshingiz ishlashda davom etadi."
   },
   {
    "name": "Oʻqituvchilik va murabbiylik",
    "pct": 72,
    "why": "Sinf oldida turish sizga oson. Faqat har bir oʻquvchining hissiy holatini payqash ustida ishlashingiz kerak boʻladi."
   }
  ]
 },
 "ES|O": {
  "areas": [
   {
    "strong": [
     [
      "Oʻzgarishga koʻnikish",
      "Koʻchish yoki yangi maktab sizni boshqalarcha qiynamaydi."
     ],
     [
      "Uyga yangilik olib kirish",
      "Oilangiz bilmagan kitob, taom yoki gʻoyani siz topib kelasiz."
     ],
     [
      "Tinch savol berish",
      "Kattalardan «nega shunday?» deb soʻrashdan tortinmaysiz, lekin bahslashmaysiz."
     ],
     [
      "Vahimasizlik",
      "Uyda muammo boʻlganda ham kayfiyatingiz keskin tushmaydi."
     ],
     [
      "Oila tarixiga qiziqish",
      "Bobongizning hikoyalarini eshitishni chinakam yoqtirasiz."
     ]
    ],
    "sub": "Uyda va yaqinlaringiz orasida",
    "title": "Oilada",
    "weak": [
     [
      "Boshlanganini tashlab qoʻyish",
      "Uyda boshlagan ishingiz yarmida qoladi va oilangiz buni sanay boshlaydi."
     ],
     [
      "Kundalik yumushga befarqlik",
      "Bir xil takrorlanadigan uy ishlari sizga chidab boʻlmas darajada zerikarli."
     ],
     [
      "Rejaga bogʻlanmaslik",
      "Oilaviy rejaga «balki» deb javob berasiz va ishonchsiz koʻrinasiz."
     ],
     [
      "Uzoqlashib qolish",
      "Oʻz qiziqishingizga shongʻib, kunlab gaplashmay qoʻyishingiz mumkin."
     ],
     [
      "Hissiyotni kam koʻrsatish",
      "Yaqinlaringiz sizni sovuq deb oʻylashi mumkin."
     ]
    ]
   },
   {
    "strong": [
     [
      "Yangi fanni tez olish",
      "Notanish mavzu sizni qoʻrqitmaydi, qiziqtiradi."
     ],
     [
      "Mustaqil oʻrganish",
      "Oʻqituvchi aytmagan manbani ham topib oʻqiysiz."
     ],
     [
      "Qiyin masalada xotirjamlik",
      "Yechilmagan masala sizni asabiylashtirmaydi."
     ],
     [
      "Tadqiqot ishlari",
      "Loyiha va referatda oʻzingizga xos yoʻl topasiz."
     ],
     [
      "Turli qarashni koʻrish",
      "Bitta javob bilan cheklanmaysiz."
     ]
    ],
    "sub": "Darsda, imtihonda va sinfdoshlar orasida",
    "title": "Maktabda",
    "weak": [
     [
      "Takrorlashga chidamaslik",
      "Bilgan mavzuni yana bir marta yozish sizga azob. Shu sababli baho pasayadi."
     ],
     [
      "Tugatilmagan topshiriq",
      "Qiziqarli qismini qilib, qolganini tashlaysiz."
     ],
     [
      "Qiziqishlar tarqoqligi",
      "Bir vaqtda beshta narsani oʻrganib, birortasini chuqurlashtirmaysiz."
     ],
     [
      "Yod olishga qarshilik",
      "Sabab tushuntirilmagan qoidani yodlash sizga toʻgʻri kelmaydi."
     ],
     [
      "Kam koʻrinish",
      "Bilsangiz ham qoʻl koʻtarmaysiz, oʻqituvchi sizni past baholashi mumkin."
     ]
    ]
   },
   {
    "strong": [
     [
      "Qiziqarli suhbatdosh",
      "Siz bilan gaplashgan odam yangi narsa bilib qoladi."
     ],
     [
      "Turlicha odamlar bilan",
      "Sizning doʻstlaringiz bir-biriga umuman oʻxshamaydi."
     ],
     [
      "Dramaga aralashmaslik",
      "Guruhdagi janjal sizni ichiga tortmaydi."
     ],
     [
      "Sarguzashtga tayyor",
      "Doʻstingiz gʻalati taklif qilsa, birinchi boʻlib siz roziligini bildirasiz."
     ],
     [
      "Hukm qilmaslik",
      "Odamning gʻayrioddiy tanlovini ham tabiiy qabul qilasiz."
     ]
    ],
    "sub": "Doʻstlik va yaqin munosabatlarda",
    "title": "Munosabatlarda",
    "weak": [
     [
      "Aloqani uzib qoʻyish",
      "Yozmay qoʻyasiz va doʻstingiz sizni yoʻqotgandek his qiladi."
     ],
     [
      "Yuzaki qolish",
      "Koʻp tanish bor, lekin haqiqiy yaqin doʻst kam."
     ],
     [
      "Qiziqish tugagach uzoqlashish",
      "Doʻstlik ham sizda yangi mavzuga oʻxshab oʻtib ketishi mumkin."
     ],
     [
      "Hissiy javob kutilganda",
      "Doʻstingiz qaygʻurganda nima deyishni bilmay qolasiz."
     ],
     [
      "Sodiqlikni koʻrsatmaslik",
      "Sizga doʻstlik muhim, lekin buni tashqaridan bilib boʻlmaydi."
     ]
    ]
   }
  ],
  "careers": [
   {
    "name": "Geologiya, geografiya, ekspeditsiya",
    "pct": 84,
    "why": "Noqulay sharoit va nomaʼlumlik sizni boshqalarchalik bezovta qilmaydi."
   },
   {
    "name": "IT va dasturlash",
    "pct": 82,
    "why": "Yangi texnologiyani oʻzingiz oʻrganib olasiz va xato sizni qoʻrqitmaydi."
   },
   {
    "name": "Ilmiy tadqiqot",
    "pct": 80,
    "why": "Javobi nomaʼlum savol ustida oylab ishlash sizni charchatmaydi."
   },
   {
    "name": "Jurnalistika va tadqiqotchilik",
    "pct": 77,
    "why": "Notanish odam va notanish joy siz uchun muammo emas."
   },
   {
    "name": "Meʼmorchilik va dizayn",
    "pct": 64,
    "why": "Yangi shakl topasiz. Uni oxirigacha chizib chiqish esa intizom talab qiladi."
   }
  ]
 },
 "E|A": {
  "areas": [
   {
    "strong": [
     [
      "Uydagi iliqlik",
      "Siz boʻlgan xonada hamma oʻzini qulay his qiladi."
     ],
     [
      "Hech kim chetda qolmaydi",
      "Jim oʻtirgan qarindoshni suhbatga siz tortasiz."
     ],
     [
      "Aloqani saqlash",
      "Uzoq qarindoshlarga qoʻngʻiroq qiladigan odam siz."
     ],
     [
      "Mehmondorchilik",
      "Uyga kelgan odam oʻzini begona his qilmaydi."
     ],
     [
      "Kayfiyat koʻtarish",
      "Uydagi ogʻir kunni yengillashtira olasiz."
     ]
    ],
    "sub": "Uyda va yaqinlaringiz orasida",
    "title": "Oilada",
    "weak": [
     [
      "Janjaldan qochish",
      "Kelishmovchilikni ochiq gapirish oʻrniga hazil bilan chetlab oʻtasiz."
     ],
     [
      "Oʻz fikrini aytmaslik",
      "Rozilikni saqlash uchun oʻz xohishingizdan voz kechasiz."
     ],
     [
      "Hamma bilan yaxshi boʻlish",
      "Ikki qarindosh urishsa, ikkalasiga ham «haqsan» deysiz."
     ],
     [
      "Tashqarida koʻproq",
      "Uy jimjit boʻlsa, doʻstlarникiga ketasiz."
     ],
     [
      "Charchaganini yashirish",
      "Kayfiyatingiz yoʻq kunda ham quvnoq koʻrinasiz."
     ]
    ]
   },
   {
    "strong": [
     [
      "Sinfni bogʻlash",
      "Sinfdagi guruhlar orasida koʻprik boʻlasiz."
     ],
     [
      "Yangi oʻquvchini qabul qilish",
      "Sinfga kelgan yangi bolani birinchi boʻlib siz kutib olasiz."
     ],
     [
      "Jamoa ruhi",
      "Guruh ishida hamma ishtirok etishini taʼminlaysiz."
     ],
     [
      "Oʻqituvchi bilan iliq",
      "Darsni ochiq va samimiy qilib yuborasiz."
     ],
     [
      "Tadbirda faol",
      "Sinf tadbirisiz siz tasavvur qilinmaydi."
     ]
    ],
    "sub": "Darsda, imtihonda va sinfdoshlar orasida",
    "title": "Maktabda",
    "weak": [
     [
      "Suhbat darsdan ustun",
      "Gaplashib, mavzuni oʻtkazib yuborasiz."
     ],
     [
      "Bahsdan qochish",
      "Notoʻgʻri javobni ham tuzatmaysiz, xafa boʻlmasin deb."
     ],
     [
      "Oʻz ishini himoya qilmaslik",
      "Bahoyingiz noadolatli qoʻyilsa ham indamaysiz."
     ],
     [
      "Diqqatning tarqoqligi",
      "Atrofda odam boʻlsa, dars ikkinchi oʻringa tushadi."
     ],
     [
      "Yolgʻiz oʻqiy olmaslik",
      "Yakka oʻtirib takrorlash sizga ogʻir."
     ]
    ]
   },
   {
    "strong": [
     [
      "Doʻst koʻp",
      "Turli davralarda oʻzingiznikisiz."
     ],
     [
      "Chetdagini koʻrish",
      "Davrada jim qolgan odamni sezasiz va yoningizga chaqirasiz."
     ],
     [
      "Quvonchni ulashish",
      "Doʻstingizning yutugʻiga oʻzingiznikidan koʻra koʻproq quvonasiz."
     ],
     [
      "Yarashtirish",
      "Urishgan ikki doʻstni yana bir dasturxonga oʻtqazasiz."
     ],
     [
      "Xotira",
      "Tugʻilgan kunlarni eslab qolasiz."
     ]
    ],
    "sub": "Doʻstlik va yaqin munosabatlarda",
    "title": "Munosabatlarda",
    "weak": [
     [
      "Hammaga ulgurmaslik",
      "Doʻst koʻp boʻlgani uchun hech biriga yetarli vaqt qolmaydi."
     ],
     [
      "«Yoʻq» deyolmaslik",
      "Charchagan boʻlsangiz ham taklifni rad etmaysiz."
     ],
     [
      "Tez ranjish",
      "Oddiy hazilni ham shaxsiy qabul qilib qoʻyasiz."
     ],
     [
      "Nizoni bostirish",
      "Muammoni gaplashish oʻrniga yopib qoʻyasiz, u esa qaytadi."
     ],
     [
      "Yoqish uchun oʻzgarish",
      "Har davrada biroz boshqacha boʻlasiz va oʻzingizni yoʻqotasiz."
     ]
    ]
   }
  ],
  "careers": [
   {
    "name": "Oʻqituvchilik va tarbiya",
    "pct": 87,
    "why": "Sinfni birlashtirish va har bir bolani koʻrish — sizning kuchingiz."
   },
   {
    "name": "HR va jamoa bilan ishlash",
    "pct": 84,
    "why": "Odamlar orasidagi keskinlikni sezasiz va hal qilasiz."
   },
   {
    "name": "Mehmondoʻstlik va turizm",
    "pct": 80,
    "why": "Odamni qulay his qildirish sizda oʻz-oʻzidan chiqadi."
   },
   {
    "name": "Jurnalistika va muloqot",
    "pct": 77,
    "why": "Notanish odam sizga ochiladi — bu suhbat olishning yarmi."
   },
   {
    "name": "Jamoat tashkilotlari va volontyorlik",
    "pct": 75,
    "why": "Odamlarni bir maqsad atrofida yigʻa olasiz."
   }
  ]
 },
 "E|C": {
  "areas": [
   {
    "strong": [
     [
      "Uydagi tadbir sizdan",
      "Tugʻilgan kun yoki mehmon — reja, roʻyxat va vaqt jadvali sizda tayyor."
     ],
     [
      "Aytilgan ish bajariladi",
      "Onangiz soʻragan narsani esdan chiqarmaysiz."
     ],
     [
      "Boshqalarni harakatga solish",
      "Uyda hamma yotgan kunda ham siz turib ish boshlaysiz va bu yuqadi."
     ],
     [
      "Oldindan oʻylash",
      "Kerakli narsa tugashidan oldin olib qoʻyasiz."
     ],
     [
      "Katta ishni boʻlaklash",
      "Bahorgi tozalash sizda bir kunda emas, rejali oʻtadi."
     ]
    ],
    "sub": "Uyda va yaqinlaringiz orasida",
    "title": "Oilada",
    "weak": [
     [
      "Buyruq ohangi",
      "Shoshilganingizda iltimos emas, koʻrsatma berib yuborasiz. Uyda bu ranjitadi."
     ],
     [
      "Sekinroqlarga sabrsizlik",
      "Ukangiz sekin qilayotgan ishni tortib olib oʻzingiz bajarasiz."
     ],
     [
      "Fikr soʻramaslik",
      "Rejani tuzib boʻlgach eʼlon qilasiz — oilangiz muhokamaga ulgurmaydi."
     ],
     [
      "Dam olishni bilmaslik",
      "Bekor oʻtirgan kuningiz oʻzingizni aybdor his qilasiz."
     ],
     [
      "Tartibsizlikdan asabiylashish",
      "Boshqalarning betartibligi sizni haddan tashqari bezovta qiladi."
     ]
    ]
   },
   {
    "strong": [
     [
      "Loyihani boshlab yuborish",
      "Guruh hali muhokama qilayotganda siz birinchi qadamni tashlagan boʻlasiz."
     ],
     [
      "Muddatga ulgurish",
      "Topshiriqni oxirgi kechaga qoldirmaysiz."
     ],
     [
      "Sinf tadbirlari",
      "Bayram yoki musobaqa boʻlsa, uyushtirish sizga topshiriladi."
     ],
     [
      "Aniq taqsimot",
      "Jamoada kim nima qilishini siz belgilaysiz va chalkashlik boʻlmaydi."
     ],
     [
      "Gapdan ishga tez oʻtish",
      "Rejani qogʻozda qoldirmaysiz."
     ]
    ],
    "sub": "Darsda, imtihonda va sinfdoshlar orasida",
    "title": "Maktabda",
    "weak": [
     [
      "Hammasini oʻzingiz qilish",
      "Ishonmaganingiz uchun jamoaning ishini ham tortib olasiz, keyin charchaysiz."
     ],
     [
      "Boshqa yechimni eshitmaslik",
      "Sizning rejangiz tayyor boʻlgani uchun yaxshiroq taklifni oʻtkazib yuborasiz."
     ],
     [
      "Reja buzilganda asabiylashish",
      "Dars jadvali kutilmaganda oʻzgarsa, kayfiyatingiz tushadi."
     ],
     [
      "Haddan ortiq yuklama",
      "Bir vaqtda uchta toʻgarakka yozilib, hech biriga ulgurmay qolasiz."
     ],
     [
      "Natijaga qarab baholash",
      "Sinfdoshingizning harakatini emas, faqat natijasini koʻrasiz."
     ]
    ]
   },
   {
    "strong": [
     [
      "Reja sizdan chiqadi",
      "«Qayerga boramiz?» degan savolga javob beradigan odam siz boʻlasiz."
     ],
     [
      "Aytgan vaqtda kelish",
      "Kechikmaysiz va doʻstlaringiz shunga ishonadi."
     ],
     [
      "Energiya berish",
      "Siz kelganingizda davra jonlanadi."
     ],
     [
      "Doʻstga amaliy yordam",
      "Achinish oʻrniga nima qilish kerakligini aytasiz va yordam berasiz."
     ],
     [
      "Yangi tanishuv",
      "Doʻstlar doirangiz tez kengayadi."
     ]
    ],
    "sub": "Doʻstlik va yaqin munosabatlarda",
    "title": "Munosabatlarda",
    "weak": [
     [
      "Rejani majburlash",
      "Doʻstlaringiz boshqacha xohlasa ham sizning variantingiz gʻolib chiqadi."
     ],
     [
      "Qatʼiyatsizlarga sabrsizlik",
      "«Bilmadim» deb turgan doʻstingizga jahlingiz chiqadi."
     ],
     [
      "Chuqur suhbatga vaqt yoʻq",
      "Doim harakatdasiz — jimgina oʻtirib gaplashish siyrak boʻladi."
     ],
     [
      "Faqat ish boʻyicha yaqinlik",
      "Doʻstlik ham loyihaga oʻxshab qoladi."
     ],
     [
      "Yordamni qabul qilmaslik",
      "«Oʻzim uddalayman» deysiz, hatto uddalay olmasangiz ham."
     ]
    ]
   }
  ],
  "careers": [
   {
    "name": "Loyiha boshqaruvi",
    "pct": 87,
    "why": "Rejani odamlarga taqsimlash va muddatni ushlab turish — sizda tabiiy."
   },
   {
    "name": "Tadbirkorlik va biznes",
    "pct": 84,
    "why": "Gapdan ishga tez oʻtasiz va boshqalarni ham qoʻzgʻata olasiz. Yangi gʻoya izlash tomonini rivojlantirishingiz kerak."
   },
   {
    "name": "Tadbir va logistika",
    "pct": 82,
    "why": "Yuzta mayda detalni bir vaqtda ushlab turish sizni charchatmaydi."
   },
   {
    "name": "Savdo va mijozlar bilan ishlash",
    "pct": 77,
    "why": "Notanish odam bilan gaplashish va kelishuvni oxiriga yetkazish."
   },
   {
    "name": "Sport murabbiyligi",
    "pct": 75,
    "why": "Mashgʻulot rejasini tuzasiz va jamoani harakatga solasiz."
   }
  ]
 },
 "E|O": {
  "areas": [
   {
    "strong": [
     [
      "Uyga jon kiritish",
      "Siz uyda boʻlsangiz, jimlik boʻlmaydi."
     ],
     [
      "Gʻoya taklif qilish",
      "Dam olish kunini qiziqarli oʻtkazish rejasi sizdan chiqadi."
     ],
     [
      "Hikoya qilish",
      "Oddiy kunni ham quvnoq qilib gapirib bera olasiz."
     ],
     [
      "Kichiklar bilan oʻyin",
      "Ukalaringiz siz bilan zerikmaydi."
     ],
     [
      "Ochiqlik",
      "Boshingizdan oʻtganini oiladan yashirmaysiz."
     ]
    ],
    "sub": "Uyda va yaqinlaringiz orasida",
    "title": "Oilada",
    "weak": [
     [
      "Tugallanmagan ish",
      "Boshlagan loyihalaringiz uyning burchagida yigʻilib qoladi."
     ],
     [
      "Uy yumushini unutish",
      "Qiziq narsa chiqsa, aytilgan ishni esdan chiqarasiz."
     ],
     [
      "Gapni boʻlish",
      "Hayajonlanganingizda boshqalarning gapini kesib oʻtasiz."
     ],
     [
      "Uyda tinch oʻtirolmaslik",
      "Oilaviy sokin kechalar sizga zerikarli tuyuladi."
     ],
     [
      "Tartib bilan orangiz",
      "Xonangiz doim tartibsiz va bu janjal sababi boʻladi."
     ]
    ]
   },
   {
    "strong": [
     [
      "Taqdimot va chiqish",
      "Sahnada oʻzingizni erkin his qilasiz."
     ],
     [
      "Ijodiy topshiriq",
      "Erkin mavzu berilsa, sizning ishingiz esda qoladi."
     ],
     [
      "Munozarada",
      "Fikr almashish sizga zavq beradi."
     ],
     [
      "Sinfni qiziqtirish",
      "Sizning savolingiz butun darsni jonlantiradi."
     ],
     [
      "Yangi gʻoyani yuqtirish",
      "Loyihaga sinfdoshlaringizni qiziqtira olasiz."
     ]
    ],
    "sub": "Darsda, imtihonda va sinfdoshlar orasida",
    "title": "Maktabda",
    "weak": [
     [
      "Muddatga ulgurmaslik",
      "Gʻoya koʻp, tugatilgan ish kam."
     ],
     [
      "Chalgʻish",
      "Darsda fikringiz boshqa narsaga ketib qoladi."
     ],
     [
      "Mashqqa chidamaslik",
      "Bir xil misolni oʻn marta yechish sizga ogʻir."
     ],
     [
      "Tartibsiz daftar",
      "Yozganingizni keyin oʻzingiz topolmaysiz."
     ],
     [
      "Baho pasayishi",
      "Bilim bor, lekin topshirilmagan ish sabab natija past."
     ]
    ]
   },
   {
    "strong": [
     [
      "Davra markazi",
      "Siz kelganingizda kayfiyat koʻtariladi."
     ],
     [
      "Odamlarni bogʻlash",
      "Turli doʻstlaringizni bir-biri bilan tanishtirasiz."
     ],
     [
      "Zerikarli boʻlmaslik",
      "Siz bilan bir kun ham bir xil oʻtmaydi."
     ],
     [
      "Ilhomlantirish",
      "Doʻstingiz tashlab qoʻygan orzusini siz esga solasiz."
     ],
     [
      "Tez yaqinlashish",
      "Notanish odam bilan bir kunda til topasiz."
     ]
    ],
    "sub": "Doʻstlik va yaqin munosabatlarda",
    "title": "Munosabatlarda",
    "weak": [
     [
      "Koʻp tanish, kam yaqin",
      "Hamma sizni biladi, lekin sizni chinakam biladigan kam."
     ],
     [
      "Vaʼdani unutish",
      "Uchrashuvni belgilab, keyin esdan chiqarasiz."
     ],
     [
      "Suhbatni egallash",
      "Gapirishni shunchalik yoqtirasizki, eshitishga vaqt qolmaydi."
     ],
     [
      "Tez sovish",
      "Yangi davra topilsa, eski doʻstlar chetda qoladi."
     ],
     [
      "Yolgʻizlikdan qochish",
      "Yolgʻiz qolmaslik uchun sizga toʻgʻri kelmaydigan davraga ham borasiz."
     ]
    ]
   }
  ],
  "careers": [
   {
    "name": "Dizayn va vizual ijod",
    "pct": 87,
    "why": "Gʻoyangiz tugamaydi va uni odamlarga koʻrsatishdan qoʻrqmaysiz."
   },
   {
    "name": "Media, blogerlik, jurnalistika",
    "pct": 84,
    "why": "Kamera yoki mikrofon oldida tabiiy qolasiz."
   },
   {
    "name": "Marketing va reklama",
    "pct": 82,
    "why": "Yangi gʻoyani odamlarga yuqtirish — bu kasbning butun mazmuni."
   },
   {
    "name": "Aktyorlik va sahna",
    "pct": 77,
    "why": "Odamlar oldida oʻzingizni erkin his qilasiz."
   },
   {
    "name": "Ijodiy fanlar oʻqituvchisi",
    "pct": 74,
    "why": "Darsni hech kim uxlab oʻtkazmaydi. Faqat jurnal va hujjat sizni zeriktiradi."
   }
  ]
 },
 "O|A": {
  "areas": [
   {
    "strong": [
     [
      "Kayfiyatni sezish",
      "Onangiz charchaganini u aytmasdan bilasiz."
     ],
     [
      "Ijodiy gʻamxoʻrlik",
      "Sizning sovgʻangiz sotib olingan emas, oʻylab topilgan boʻladi."
     ],
     [
      "Hech kimni ayblamaslik",
      "Uydagi xatoni kimningdir aybi deb qidirmaysiz."
     ],
     [
      "Boshqacha fikrni tinglash",
      "Kattalar bilan bahslashmay, ularni tushunishga harakat qilasiz."
     ],
     [
      "Uyni chiroyli qilish",
      "Xonani, dasturxonni siz oʻzgacha bezaysiz."
     ]
    ],
    "sub": "Uyda va yaqinlaringiz orasida",
    "title": "Oilada",
    "weak": [
     [
      "Oilaning dardini oʻziga olish",
      "Uydagi muammo sizni boshqalardan koʻra koʻproq ezadi."
     ],
     [
      "Amaliy tomondan uzoq",
      "Pul, jadval va rejaga eʼtiborsizsiz."
     ],
     [
      "Toʻqnashuvdan qochish",
      "Norozi boʻlsangiz ham ochiq aytmaysiz."
     ],
     [
      "Ideallashtirish",
      "Oilangizni mukammal deb tasavvur qilasiz, kamchilik koʻrsangiz qattiq ranjiysiz."
     ],
     [
      "Ichiga yopilish",
      "Xafa boʻlganingizda xonangizga kirib ketasiz."
     ]
    ]
   },
   {
    "strong": [
     [
      "Ijodiy loyiha",
      "Erkin topshiriqda ishingiz esda qoladigan boʻladi."
     ],
     [
      "Qiynalgan sinfdoshga yordam",
      "Tushunmagan bolani hech kim bilmagan holda oʻrgatasiz."
     ],
     [
      "Axloqiy savollar",
      "«Bu adolatlimi?» degan savolni siz berasiz."
     ],
     [
      "Raqobatsizlik",
      "Baho uchun talashmaysiz, sinf tinch boʻladi."
     ],
     [
      "Estetik did",
      "Daftar, taqdimot va rasm sizda chiroyli chiqadi."
     ]
    ],
    "sub": "Darsda, imtihonda va sinfdoshlar orasida",
    "title": "Maktabda",
    "weak": [
     [
      "Tanqidga taʼsirchanlik",
      "Oʻqituvchining kichik tanbehi ham kayfiyatingizni kunlab buzadi."
     ],
     [
      "Tartibsizlik",
      "Muddat va jadval sizni chalkashtiradi."
     ],
     [
      "Qiziqmagan fanni tashlash",
      "Yoqmagan fanga umuman kuch sarflamaysiz."
     ],
     [
      "Oʻzini past baholash",
      "Matematikada qiynalsangiz, ijodiy iqtidoringizni ham kamsitasiz."
     ],
     [
      "Ovoz chiqarmaslik",
      "Yaxshi gʻoyangiz bor, lekin sinf oldida aytmaysiz."
     ]
    ]
   },
   {
    "strong": [
     [
      "Chuqur suhbat",
      "Yuzaki gap sizga qiziq emas, siz asosiy narsani soʻraysiz."
     ],
     [
      "Hukmsiz qabul",
      "Doʻstingiz eng uyaladigan narsasini ham sizga aytadi."
     ],
     [
      "Sezgirlik",
      "Ovoz ohangidan kayfiyatni bilasiz."
     ],
     [
      "Oʻziga xos yaqinlik",
      "Sizning doʻstligingiz boshqalarnikiga oʻxshamaydi."
     ],
     [
      "Kechirimlilik",
      "Xatoni uzoq eslab yurmaysiz."
     ]
    ],
    "sub": "Doʻstlik va yaqin munosabatlarda",
    "title": "Munosabatlarda",
    "weak": [
     [
      "Ogʻriqni oʻziga olish",
      "Doʻstingizning muammosi sizni uning oʻzidan koʻra koʻproq qiynaydi."
     ],
     [
      "Ideallashtirish",
      "Odamni mukammal deb bilasiz, keyin haqiqatni koʻrib qattiq hafsalangiz pir boʻladi."
     ],
     [
      "Uzoqlashib ketish",
      "Ranjiganingizda tushuntirmay, jimgina yoʻqolasiz."
     ],
     [
      "Chegara qoʻyolmaslik",
      "Doʻstingiz uchun oʻz vaqtingizni butunlay berasiz."
     ],
     [
      "Nizodan qochish",
      "Muammoni aytish oʻrniga munosabatni sovutasiz."
     ]
    ]
   }
  ],
  "careers": [
   {
    "name": "Psixologiya va terapiya",
    "pct": 87,
    "why": "Odamni tushunish va yangi yondashuv izlash bir joyda kerak boʻladi."
   },
   {
    "name": "Ijtimoiy ish va nodavlat tashkilotlar",
    "pct": 82,
    "why": "Muammoni koʻrganingizda avval odamlar haqida oʻylaysiz."
   },
   {
    "name": "Sanʼat va arttеrapiya",
    "pct": 82,
    "why": "Ijod orqali odamga yordam berish — ikkala kuchingiz birga ishlaydi."
   },
   {
    "name": "Adabiyot va tarjima",
    "pct": 77,
    "why": "Soʻz orqali odamning ichki dunyosini yetkazish sizga yaqin."
   },
   {
    "name": "Maxsus pedagogika",
    "pct": 74,
    "why": "Har bolaga alohida yoʻl kerak — siz uni topa olasiz."
   }
  ]
 },
 "O|C": {
  "areas": [
   {
    "strong": [
     [
      "Amaliy yechim topish",
      "Uydagi buzilgan narsani siz oʻzingizcha tuzatib qoʻyasiz."
     ],
     [
      "Aytilgan ish bajariladi",
      "Vaʼda bergan boʻlsangiz, eslatish shart emas."
     ],
     [
      "Uzoqni oʻylash",
      "Kelasi yilgi imtihon haqida bugundan gapirasiz."
     ],
     [
      "Tartib",
      "Sizning burchagingiz uyning eng tartibli joyi."
     ],
     [
      "Yaxshilashga intilish",
      "Bir marta qilingan ishni keyingi safar yaxshiroq qilasiz."
     ]
    ],
    "sub": "Uyda va yaqinlaringiz orasida",
    "title": "Oilada",
    "weak": [
     [
      "Mukammallik talabi",
      "Oʻzingizga ham, oilangizga ham juda baland talab qoʻyasiz."
     ],
     [
      "Boshqacha usulni tanqid",
      "Onangiz boshqacha qilsa, «notoʻgʻri» deb aytib yuborasiz."
     ],
     [
      "Qaror oʻzgarmasligi",
      "Bir marta rejalashtirgan narsangizni oʻzgartirish sizga ogʻir."
     ],
     [
      "Dam olishni bilmaslik",
      "Bekorchilik sizga vaqtni behuda sarflashdek tuyuladi."
     ],
     [
      "Hissiyot oʻrniga vazifa",
      "Yaqiningiz qaygʻurganda unga reja tuzib berasiz, quchoqlash oʻrniga."
     ]
    ]
   },
   {
    "strong": [
     [
      "Loyiha oxirigacha",
      "Boshlagan ishingizni tugatasiz — sinfda bu kam."
     ],
     [
      "Original yechim",
      "Hammadan boshqacha, lekin ishlaydigan yoʻl topasiz."
     ],
     [
      "Aniq rejalashtirish",
      "Katta topshiriqni haftalarga boʻlasiz."
     ],
     [
      "Yuqori sifat",
      "Sizning ishingiz koʻrinishidan ham puxta."
     ],
     [
      "Mustaqil ishlash",
      "Nazorat kerak emas."
     ]
    ],
    "sub": "Darsda, imtihonda va sinfdoshlar orasida",
    "title": "Maktabda",
    "weak": [
     [
      "Mukammallik sekinlashtiradi",
      "Yetarlicha yaxshi ishni ham qayta qilaverib, muddatdan chiqasiz."
     ],
     [
      "Oʻzini qattiq tanqid",
      "Bitta xato butun ishni bekor qilgandek tuyuladi."
     ],
     [
      "Jamoa bilan qiyinchilik",
      "Sinfdoshingiz sizchalik jiddiy emasligi sizni asabiylashtiradi."
     ],
     [
      "Yordam soʻramaslik",
      "Yolgʻiz qilishni afzal koʻrasiz, garchi ikki barobar koʻp vaqt ketsa ham."
     ],
     [
      "Ortiqcha yuklanish",
      "Dam olmay ishlab, imtihon oldidan charchab qolasiz."
     ]
    ]
   },
   {
    "strong": [
     [
      "Ishonchli soʻz",
      "Aytgan vaqtingizda kelasiz va aytganingizni qilasiz."
     ],
     [
      "Oʻylangan sovgʻa",
      "Sizning sovgʻangiz tasodifiy boʻlmaydi."
     ],
     [
      "Amaliy maslahat",
      "Doʻstingiz muammosiga aniq qadamlar taklif qilasiz."
     ],
     [
      "Kam, lekin chuqur",
      "Doʻstlaringiz kam, ammo yillar davom etadi."
     ],
     [
      "Aytganini eslash",
      "Doʻstingiz oʻtgan oyda aytgan gapini esda tutasiz."
     ]
    ],
    "sub": "Doʻstlik va yaqin munosabatlarda",
    "title": "Munosabatlarda",
    "weak": [
     [
      "Vaqt topolmaslik",
      "Rejangiz zich va doʻstlarga oʻrin qolmaydi."
     ],
     [
      "Tanlovlarini baholash",
      "Doʻstingizning yengil qarorini ichingizda maʼqullamaysiz va bu sezilib qoladi."
     ],
     [
      "Rejasiz uchrashuvdan noqulaylik",
      "«Hozir chiq» degan taklif sizni bezovta qiladi."
     ],
     [
      "Yumshoq boʻlolmaslik",
      "Toʻgʻri gapni juda toʻgʻri aytib yuborasiz."
     ],
     [
      "Doiraning torligi",
      "Yangi odam qoʻshilishi sizga koʻp vaqt oladi."
     ]
    ]
   }
  ],
  "careers": [
   {
    "name": "Muhandislik va texnika",
    "pct": 87,
    "why": "Yangi yechim topasiz va uni chizmagacha, hisobgacha olib borasiz."
   },
   {
    "name": "Meʼmorchilik",
    "pct": 82,
    "why": "Gʻoya va oʻlchov bir odamda birga boʻlishi shart — bu siz."
   },
   {
    "name": "Dasturlash va tizim loyihalash",
    "pct": 82,
    "why": "Murakkab masalani aniq qadamlarga boʻlish sizga tabiiy."
   },
   {
    "name": "Ilmiy tadqiqot",
    "pct": 82,
    "why": "Uzoq muddatli, natijasi kechikadigan ish sizni qoʻrqitmaydi."
   },
   {
    "name": "Mahsulot va loyiha dizayni",
    "pct": 74,
    "why": "Gʻoyani jadvalga aylantirasiz. Jamoaga tushuntirish tomonini rivojlantirishingiz kerak."
   }
  ]
 }
};
