# -*- coding: utf-8 -*-
u"""Emits assets/values.js — the browser copy of the Work Values bank.

One file, all three languages, like career.js and unlike life-*.js: ten items is
about 3 KB per language, so bundling costs less than splitting would save, and
the items are needed DURING the test where a late-arriving pack would truncate
it rather than merely drop a section.

Refuses to write until values_check.py passes.

    python build_values_js.py
"""
import io, json, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import values_content as vc

OUT = 'C:/Users/Asus/TestMind-site/assets/values.js'
LANGS = ['uz', 'ru', 'en']


def _gate(script, target):
    u"""Run a checker and refuse to emit `target` unless it passes.

    The child's stdout is a pipe, and on Windows a piped Python process encodes
    with the system codepage rather than UTF-8 -- so a checker that prints Uzbek
    or Russian dies with UnicodeEncodeError and reports failure for a reason that
    has nothing to do with the data. PYTHONIOENCODING settles that, and the
    output is printed on failure instead of being swallowed, because a gate that
    hides why it closed is worse than no gate.
    """
    env = dict(os.environ)
    env['PYTHONIOENCODING'] = 'utf-8'
    r = subprocess.run([sys.executable, os.path.join(HERE, script)],
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                       env=env)
    if r.returncode != 0:
        sys.stdout.write(r.stdout.decode('utf-8', 'replace'))
        raise SystemExit('%s failed -- refusing to emit %s' % (script, target))

def build():
    _gate('values_check.py', 'values.js')

    data = {}
    for lang in LANGS:
        h, p = vc.intro_for(lang)
        data[lang] = {
            'labels': vc.labels_for(lang),
            'names': vc.names_for(lang),
            'introH': h, 'introP': p,
            # d = dimension, t = text. Order and keying come from the Uzbek
            # original in every language, so a translation cannot move an item
            # onto another value.
            'items': [{'d': d, 't': t} for d, t in vc.items_for(lang)],
        }

    js = (u'// GENERATED by tools/build_values_js.py from values_content.py — do not edit.\n'
          u'//\n'
          u'// Work Values: what a student wants FROM a job. The response scale is\n'
          u'// importance, which is neither the personality scale (agreement) nor the\n'
          u'// career scale (liking), so the labels travel with the bank.\n'
          u'var VALUE_DIMS = %s;\n'
          u'var VALUE_LANGS = %s;\n' % (
              json.dumps(vc.DIMENSIONS),
              json.dumps(data, ensure_ascii=False, indent=1, sort_keys=True)))
    io.open(OUT, 'w', encoding='utf-8', newline='').write(js)
    print('wrote values.js  %d items x %d dimensions x %d languages, %d KB'
          % (len(vc.ITEMS), len(vc.DIMENSIONS), len(LANGS), len(js.encode('utf-8')) // 1024))


if __name__ == '__main__':
    build()
