# -*- coding: utf-8 -*-
u"""Emits assets/school.js: the browser copy of the school subjects bank.

One file, all three languages, like career.js and values.js. Thirty three items
is about 4 KB per language, and the items are needed DURING the challenge, where
a late arriving language pack would truncate it rather than merely drop a
section below the fold.

Refuses to write until school_check.py passes.

    python build_school_js.py
"""
import io
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import school_content as sc

OUT = 'C:/Users/Asus/TestMind-site/assets/school.js'
LANGS = ['uz', 'ru', 'en']


def _gate(script, target):
    u"""Run a checker and refuse to emit `target` unless it passes.

    PYTHONIOENCODING is set for the same reason build_values_js.py sets it: on
    Windows a piped child encodes with the system codepage, so a checker that
    prints Uzbek or Russian dies with UnicodeEncodeError and reports failure for
    a reason that has nothing to do with the data.
    """
    env = dict(os.environ)
    env['PYTHONIOENCODING'] = 'utf-8'
    r = subprocess.run([sys.executable, os.path.join(HERE, script)],
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                       env=env)
    if r.returncode != 0:
        sys.stdout.write(r.stdout.decode('utf-8', 'replace'))
        raise SystemExit('%s failed -- refusing to emit %s' % (script, target))


def build():
    _gate('school_check.py', 'school.js')

    data = {}
    for lang in LANGS:
        head, blurb = sc.title_for(lang)
        data[lang] = {
            'labels': sc.labels_for(lang),
            'names': sc.names_for(lang),
            'title': head,
            'blurb': blurb,
            # s = subject, f = facet, r = reverse, t = text. The keying comes
            # from the Uzbek original in every language, so a translation cannot
            # move an item onto another subject or another facet.
            'items': sc.items_for(lang),
            'sections': [{'f': f, 'h': h} for f, h in sc.sections_for(lang)],
        }

    js = (u'// GENERATED by tools/build_school_js.py from school_content.py. Do not edit.\n'
          u'//\n'
          u'// How school feels: eleven subjects asked three ways. The response scale is\n'
          u'// agreement, the same five points as the personality bank, because a student\n'
          u'// meets both in one sitting and a second wording would read as a new scale.\n'
          u'//\n'
          u'// Cost items carry r:1 and are REVERSE scored. A student who dreads a subject\n'
          u'// is telling you something that counts against it, not for it.\n'
          u'var SCHOOL_SUBJECTS = %s;\n'
          u'var SCHOOL_FACETS = %s;\n'
          u'var SCHOOL_LANGS = %s;\n' % (
              json.dumps(sc.SUBJECTS),
              json.dumps([f for f, _, _ in sc.FACETS]),
              json.dumps(data, ensure_ascii=False, indent=1, sort_keys=True)))
    io.open(OUT, 'w', encoding='utf-8', newline='').write(js)
    print('wrote school.js  %d items x %d subjects x %d languages, %d KB'
          % (len(sc.items_for('uz')), len(sc.SUBJECTS), len(LANGS),
             len(js.encode('utf-8')) // 1024))


if __name__ == '__main__':
    build()
