# -*- coding: utf-8 -*-
u"""Emits assets/career.js — the browser copy of the RIASEC bank.

ONE FILE, ALL THREE LANGUAGES -- deliberately different from life.js, which is
split per language. The life packs are 45-67 KB each, so bundling them would
have sent a student ~110 KB of text they cannot read. The career bank is about
6 KB per language. Bundling all three costs less than test-ru.js already does,
and in exchange the items are on the page synchronously: they are needed DURING
the test, right after the personality section, and a pack that arrives late or
not at all would truncate the test instead of merely dropping a section.

Refuses to write anything until riasec_check.py passes, because a bank with an
item on the wrong scale scores every student wrongly and looks entirely normal.

    python build_career_js.py
"""
import io, json, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import riasec_content as rc

OUT = 'C:/Users/Asus/TestMind-site/assets/career.js'
LANGS = ['uz', 'ru', 'en']


def build():
    check = subprocess.call([sys.executable, os.path.join(HERE, 'riasec_check.py')],
                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if check != 0:
        raise SystemExit('riasec_check.py failed -- refusing to emit career.js')

    data = {}
    for lang in LANGS:
        items = rc.items_for(lang)
        data[lang] = {
            'labels': rc.labels_for(lang),
            'scaleNames': rc.scale_names_for(lang),
            'scaleLeads': rc.scale_leads_for(lang),
            'attribution': rc.attribution_for(lang),
            # s = RIASEC scale, t = text, late = held back for the top-up block.
            # Order is identical across languages; the scale and the late flag
            # come from the Uzbek original in every language, so a translation
            # cannot move an item onto another scale.
            'items': [{'s': s, 't': t, 'late': l} for s, t, l in items],
        }

    js = (u'// GENERATED by tools/build_career_js.py from riasec_content.py — do not edit.\n'
          u'//\n'
          u'// Career-interest items (RIASEC). The response scale is like/dislike, NOT\n'
          u'// agreement like the personality items, so the labels travel with the bank.\n'
          u'//\n'
          u'// %s\n'
          u'var CAREER_SCALES = %s;\n'
          u'var CAREER_LANGS = %s;\n' % (
              rc.ATTRIBUTION.replace(u'\n', u' '),
              json.dumps(rc.SCALES),
              json.dumps(data, ensure_ascii=False, indent=1, sort_keys=True)))
    io.open(OUT, 'w', encoding='utf-8', newline='').write(js)

    n = len(data['uz']['items'])
    core = sum(1 for i in data['uz']['items'] if not i['late'])
    print('wrote career.js  %d items (%d core + %d reserve) x %d languages, %d KB'
          % (n, core, n - core, len(LANGS), len(js.encode('utf-8')) // 1024))


if __name__ == '__main__':
    build()
