# -*- coding: utf-8 -*-
u"""Emits life-<lang>.js — the browser copy of life_content.py.

test.html is a standalone client-side app and cannot read a Python module, so
the module is compiled to JS here rather than retyped. Same arrangement as
characters.js + strings.js: one source, two consumers, no way to disagree.

The two consumers no longer show the same thing, and both differences are
deliberate:

  AREAS.  The archetype page prints all three of Oilada / Maktabda /
  Munosabatlarda, thirty bullets in total. Someone browsing /types/ came to
  read about a character and will. A student who has just answered ninety
  questions will not, and the section they gave up in sat directly above
  «Yoʻnalishlar» — the part they came for. So this file emits one merged block
  of four strengths and four watch-outs, chosen in OVERALL in life_content.py.

  DIRECTIONS.  Not emitted at all. The archetype page still ranks them with a
  percentage; on the result screen «Yoʻnalishlar» ranks careers one scroll
  below from interests, values, marks and personality, and over 3,600 simulated
  students the two lists' top picks agreed 9.4% of the time against a 6.3%
  chance baseline. Two answers to one question, and the louder one had the
  thinner evidence.

    python build_life_js.py
"""
import io, json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import life_content as lc
from i18n import LANGS

OUT = 'C:/Users/Asus/TestMind-site/assets/life-%s.js'


def pack(lang):
    u"""Every archetype written in this language, keyed by archetype."""
    src = lc.LIFE_BY_LANG.get(lang) or {}
    data = {}
    for key in lc.LIFE:                      # Uzbek decides which archetypes exist
        if key not in src:
            continue                         # not written in this language yet
        lc.check_translation(key, lang)      # refuse a half-written one, loudly
        # One merged block, not three areas. overall_for() selects by position,
        # so all three languages get the same four bullets rather than whichever
        # four a translator happened to like.
        o = lc.overall_for(key, lang)
        data[key] = {'strong': [[t, p] for t, p in o['strong']],
                     'weak': [[t, p] for t, p in o['weak']]}
    return data


def build():
    u"""One file per language, not one file with three languages in it.

    A student reads their own language and nothing else, and this is the single
    biggest asset the test page pulls -- bundling all three would put ~110 KB of
    text no reader will ever see onto a phone on a school connection. Each file
    declares the same two names, so the result screen has one code path and the
    loader simply picks a URL.
    """
    for lang in LANGS:
        data = pack(lang)
        # Only the two column headers survive. `career`/`result_career` and the
        # two notes went with the directions block they introduced.
        labels = {'strong': lc.LABELS[lang]['strong'],
                  'weak': lc.LABELS[lang]['weak']}
        js = (u'// GENERATED by tools/build_life_js.py from life_content.py — do not edit.\n'
              u'// Language: %s. One merged strengths/watch-outs block per archetype; the\n'
              u'// three life areas and the directions list stay on the archetype pages.\n'
              u'var LIFE_LABELS = %s;\nvar LIFE = %s;\n' % (
                  lang,
                  json.dumps(labels, ensure_ascii=False, indent=1, sort_keys=True),
                  json.dumps(data, ensure_ascii=False, indent=1, sort_keys=True)))
        path = OUT % lang
        io.open(path, 'w', encoding='utf-8', newline='').write(js)
        n_lines = sum(len(e['strong']) + len(e['weak']) for e in data.values())
        print('wrote %-14s %2d archetypes, %3d bullets, %3d KB'
              % (os.path.basename(path), len(data), n_lines,
                 len(js.encode('utf-8')) // 1024))


if __name__ == '__main__':
    build()
