# -*- coding: utf-8 -*-
u"""Lift the Wikipedia links out of Naseeb Edu's figures.js into assets/figure-wiki.js.

Naseeb Edu's result panel ends each figure with a link straight out to Wikipedia,
rather than a paragraph of our own: the point is that a student can go and read
about a real person, and a summary we wrote about them is not that. TestMind
already names the same twenty figures, keyed identically, but carries no links.

Generated rather than retyped, so the two projects cannot drift apart on which
person a link points at. Re-run after Naseeb Edu's scripts/gen_figures.mjs.

    python tools/build_figure_wiki.py
"""
import io
import json
import os
import re

SRC = 'C:/Users/Asus/naseeb-edu-demo/frontend/src/figures.js'
OUT = 'C:/Users/Asus/TestMind-site/assets/figure-wiki.js'
LANGS = ('uz', 'ru', 'en')


def load():
    src = io.open(SRC, encoding='utf-8').read()
    m = re.search(r'=\s*(\{[\s\S]*?\n\})', src)
    if not m:
        raise SystemExit('figures.js: could not find the object literal')
    return json.loads(m.group(1))


def main():
    if not os.path.exists(SRC):
        raise SystemExit('Naseeb Edu is not checked out at %s' % SRC)
    data = load()

    links = {}
    for key in sorted(data):
        for gender in ('male', 'female'):
            fig = data[key].get(gender)
            if not fig:
                raise SystemExit('%s: no %s figure' % (key, gender))
            wiki = fig.get('wiki') or {}
            missing = [l for l in LANGS if not wiki.get(l)]
            if missing:
                raise SystemExit('%s/%s (%s): no %s link'
                                 % (key, gender, fig.get('who'), ', '.join(missing)))
            links.setdefault(key, {})[gender] = dict((l, wiki[l]) for l in LANGS)

    if len(links) != 10:
        raise SystemExit('expected ten archetypes, found %d' % len(links))

    body = json.dumps(links, ensure_ascii=False, indent=2, sort_keys=True)
    out = (u'// GENERATED by tools/build_figure_wiki.py -- do not edit by hand.\n'
           u'//\n'
           u'// Wikipedia links for the twenty historical figures, lifted from Naseeb Edu\n'
           u'// so both projects point at the same people. The result panel links straight\n'
           u'// out rather than summarising: a student should be able to go and read about\n'
           u'// a real person, and a paragraph we wrote about them is not that.\n'
           u'//\n'
           u'// Keyed by archetype, then male/female, then language.\n'
           u'var FIGURE_WIKI = %s;\n' % body)
    io.open(OUT, 'w', encoding='utf-8', newline='').write(out)
    print('wrote %-34s %6d bytes (%d archetypes, %d links)'
          % ('assets/figure-wiki.js', len(out.encode('utf-8')),
             len(links), len(links) * 2 * len(LANGS)))


if __name__ == '__main__':
    main()
