# -*- coding: utf-8 -*-
u"""Emits life.js — the browser copy of life_content.py.

The result screen in test.html needs the same Oilada / Maktabda /
Munosabatlarda detail that the archetype pages show, but test.html is a
standalone client-side app: it cannot read a Python module. So the module is
compiled to JS here rather than retyped, which is the same arrangement as
characters.js + strings.js — one source, two consumers, no way for them to
disagree.

The DIRECTIONS are the one place where the two consumers deliberately differ.
The archetype page ranks them and prints a percentage; this file emits neither.
A visitor browsing /types/ sees that list on its own, but on the result screen
it lands a single scroll above «Yoʻnalishlar», which ranks careers from
interests, values, marks and personality. Two ranked lists built from almost
disjoint evidence disagree for most students, and the one with the weaker
evidence was the one shouting a number. See RESULT_CAREER_TITLE in
life_content.py.

    python build_life_js.py
"""
import io, json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import life_content as lc
from i18n import LANGS

OUT = 'C:/Users/Asus/TestMind-site/assets/life-%s.js'


def pack(lang):
    u"""Every archetype written in this language, keyed by archetype."""
    src = lc.LIFE_BY_LANG.get(lang) or {}
    labels = lc.LABELS[lang]
    data = {}
    for key in lc.LIFE:                      # Uzbek decides which archetypes exist
        if key not in src:
            continue                         # not written in this language yet
        lc.check_translation(key, lang)      # refuse a half-written one, loudly
        d = src[key]
        entry = {'areas': [], 'careers': []}
        for area in ('family', 'school', 'friends'):
            if area not in d:
                continue
            title, sub = labels['areas'][area]
            entry['areas'].append({
                'title': title, 'sub': sub,
                'strong': [[t, p] for t, p in d[area]['strong']],
                'weak': [[t, p] for t, p in d[area]['weak']],
            })
        # NO PERCENTAGE, AND NO RANK. The archetype page still shows both; the
        # result screen deliberately does not, because «Yoʻnalishlar» ranks
        # careers one scroll below from four signals rather than from two
        # personality traits, and two disagreeing ranked lists on one screen is
        # the thing a parent points at. See RESULT_CAREER_TITLE in
        # life_content.py for the measurement behind that.
        #
        # Alphabetical, so the order cannot be read as a ranking by accident.
        # It differs between languages because the names do, which is fine here
        # and would not have been while these carried a number.
        for name, weights, why in lc.careers_for(key, lang):
            entry['careers'].append({'name': name, 'why': why})
        entry['careers'].sort(key=lambda c: c['name'])
        data[key] = entry
    return data


def build():
    u"""One file per language, not one file with three languages in it.

    A student reads their own language and nothing else, and this is the single
    biggest asset the test page pulls -- bundling all three would put ~110 KB of
    text no reader will ever see onto a phone on a school connection. Each file
    declares the same two names, so the result screen has one code path and the
    loader simply picks a URL.
    """
    for lang in LANGS:
        data = pack(lang)
        # `careers`/`note` deliberately take the result-screen wording, not the
        # archetype page's `career`/`disclaimer` -- the latter two talk about
        # percentages that this file no longer emits.
        labels = {'strong': lc.LABELS[lang]['strong'],
                  'weak': lc.LABELS[lang]['weak'],
                  'careers': lc.LABELS[lang]['result_career'],
                  'note': lc.LABELS[lang]['result_note']}
        js = (u'// GENERATED by tools/build_life_js.py from life_content.py — do not edit.\n'
              u'// Language: %s. Directions carry no percentage and no rank here: on the\n'
              u'// result screen «Yoʻnalishlar» is the only thing that ranks careers.\n'
              u'var LIFE_LABELS = %s;\nvar LIFE = %s;\n' % (
                  lang,
                  json.dumps(labels, ensure_ascii=False, indent=1, sort_keys=True),
                  json.dumps(data, ensure_ascii=False, indent=1, sort_keys=True)))
        path = OUT % lang
        io.open(path, 'w', encoding='utf-8', newline='').write(js)
        n_lines = sum(len(a['strong']) + len(a['weak'])
                      for e in data.values() for a in e['areas'])
        print('wrote %-14s %2d archetypes, %3d bullets, %2d directions, %3d KB'
              % (os.path.basename(path), len(data), n_lines,
                 sum(len(e['careers']) for e in data.values()),
                 len(js.encode('utf-8')) // 1024))


if __name__ == '__main__':
    build()
