# -*- coding: utf-8 -*-
u"""Emits assets/wil.js: the browser copy of the Work Importance bank.

Twenty cards is small enough that all three languages fit in one file, like
values.js. The multipliers are computed here and written out rather than being
recomputed in the browser, so the weighting has exactly one definition and
wil_check.py is the thing that guards it.

Refuses to write until wil_check.py passes.

    python build_wil_js.py
"""
import io
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import wil_content as wc

OUT = 'C:/Users/Asus/TestMind-site/assets/wil.js'
LANGS = ['uz', 'ru', 'en']


def _gate(script, target):
    u"""Run a checker and refuse to emit `target` unless it passes."""
    env = dict(os.environ)
    env['PYTHONIOENCODING'] = 'utf-8'
    r = subprocess.run([sys.executable, os.path.join(HERE, script)],
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                       env=env)
    if r.returncode != 0:
        sys.stdout.write(r.stdout.decode('utf-8', 'replace'))
        raise SystemExit('%s failed -- refusing to emit %s' % (script, target))


def build():
    _gate('wil_check.py', 'wil.js')

    data = {}
    for lang in LANGS:
        head, blurb = wc.title_for(lang)
        data[lang] = {
            'levels': wc.levels_for(lang),
            'names': wc.names_for(lang),
            'leads': wc.leads_for(lang),
            'stem': wc.stem_for(lang),
            'title': head,
            'blurb': blurb,
            # c = card letter, v = value, t = text. Letter and value come from
            # the Uzbek original in every language.
            'cards': [{'c': c, 'v': v, 't': t} for c, v, t in wc.cards_for(lang)],
        }

    js = (u'// GENERATED by tools/build_wil_js.py from wil_content.py. Do not edit.\n'
          u'//\n'
          u'// Work Importance: twenty cards sorted into five personal importance levels.\n'
          u'// Each level can contain any number of cards; the student supplies the\n'
          u'// distribution that reflects their own perspective.\n'
          u'//\n'
          u'// Items are the O*NET Work Importance Locator, US Department of Labor, public\n'
          u'// domain. The repeated stem is lifted out and shown once above the cards.\n'
          u'//\n'
          u'// Scores are averages within each value, so unequal card counts do not\n'
          u'// give one value an automatic advantage.\n'
          u'var WIL_VALUES = %s;\n'
          u'var WIL_LANGS = %s;\n' % (
              json.dumps(wc.VALUES),
              json.dumps(data, ensure_ascii=False, indent=1, sort_keys=True)))
    io.open(OUT, 'w', encoding='utf-8', newline='').write(js)
    print('wrote wil.js  %d cards x %d values x %d languages, %d KB'
          % (len(wc.CARDS), len(wc.VALUES), len(LANGS), len(js.encode('utf-8')) // 1024))


if __name__ == '__main__':
    build()
