# -*- coding: utf-8 -*-
u"""Emits assets/careers-data.js — the browser copy of the career taxonomy.

Structure from careers.py, names from careers_text_*.py, paired by key. All
three languages in one file: only the NAMES are translated, and 33 short names
per language is about 2 KB, so splitting would cost more than it saves.

    python build_careers_js.py
"""
import io, json, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import careers as cr
import subjects as sj
import careers_text_uz as _uz
import careers_text_ru as _ru
import careers_text_en as _en

OUT = 'C:/Users/Asus/TestMind-site/assets/careers-data.js'
TEXT = {'uz': _uz, 'ru': _ru, 'en': _en}


def _gate(script, target):
    env = dict(os.environ); env['PYTHONIOENCODING'] = 'utf-8'
    r = subprocess.run([sys.executable, os.path.join(HERE, script)],
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT, env=env)
    if r.returncode != 0:
        sys.stdout.write(r.stdout.decode('utf-8', 'replace'))
        raise SystemExit('%s failed -- refusing to emit %s' % (script, target))


def build():
    _gate('careers_check.py', 'careers-data.js')
    _gate('subjects_check.py', 'careers-data.js')

    fams = {}
    for f in cr.populated_families():
        fams[f] = {'riasec': cr.FAMILIES[f], 'subjects': cr.FAMILY_SUBJECTS[f],
                   'values': cr.FAMILY_VALUES[f]}

    def entries(table, getter):
        out = {}
        for key in sorted(table):
            e = getter(key)
            if e['family'] not in fams:
                continue                       # family not populated yet
            out[key] = {'family': e['family'], 'riasec': e['riasec'],
                        'subjects': e['subjects'], 'values': cr.values_of(key),
                        'education': e['education']}
        return out

    names = {}
    for lang, mod in TEXT.items():
        names[lang] = {'families': mod.FAMILIES, 'careers': mod.CAREERS, 'majors': mod.MAJORS,
                       # The subject-entry form and the "subjects to strengthen"
                       # line both need these, and they lived only in Python.
                       'subjects': sj.names_for(lang)}

    js = (u'// GENERATED by tools/build_careers_js.py — do not edit.\n'
          u'//\n'
          u'// Structure (family, RIASEC, subjects, work values, education level) is\n'
          u'// language-neutral and comes from careers.py. Only NAMES are translated, so\n'
          u'// a translation can never move a career onto a different profile.\n'
          u'//\n'
          u'// No salaries, no demand ratings, no employment forecasts: there is no Uzbek\n'
          u'// labour-market data behind them and a fifteen-year-old would believe them.\n'
          u'var CAREER_FAMILIES = %s;\n'
          u'var CAREER_ENTRIES = %s;\n'
          u'var MAJOR_ENTRIES = %s;\n'
          u'var SUBJECT_KEYS = %s;\n'
          u'var SUBJECT_SCALES = %s;\n'
          u'var TAXONOMY_NAMES = %s;\n' % (
              json.dumps(fams, ensure_ascii=False, indent=1, sort_keys=True),
              json.dumps(entries(cr.CAREERS, cr.career), ensure_ascii=False, indent=1, sort_keys=True),
              json.dumps(entries(cr.MAJORS, cr.major), ensure_ascii=False, indent=1, sort_keys=True),
              json.dumps(sj.SUBJECT_KEYS),
              json.dumps({'scales': sj.SCALES, 'weights': sj.SOURCE_WEIGHT},
                         ensure_ascii=False, sort_keys=True),
              json.dumps(names, ensure_ascii=False, indent=1, sort_keys=True)))
    io.open(OUT, 'w', encoding='utf-8', newline='').write(js)
    print('wrote careers-data.js  %d families, %d careers, %d majors, %d KB'
          % (len(fams), len(entries(cr.CAREERS, cr.career)),
             len(entries(cr.MAJORS, cr.major)), len(js.encode('utf-8')) // 1024))


if __name__ == '__main__':
    build()
