# -*- coding: utf-8 -*-
u"""Emits life.js — the browser copy of life_content.py.

The result screen in test.html needs the same Oilada / Maktabda /
Munosabatlarda detail and the same ranked directions that the archetype pages
show, but test.html is a standalone client-side app: it cannot read a Python
module. So the module is compiled to JS here rather than retyped, which is the
same arrangement as characters.js + strings.js — one source, two consumers,
no way for them to disagree.

The percentages are baked in already computed. Recomputing them in JS would
mean shipping the weights and the HIGH/MID constants and trusting two
implementations to round identically; emitting the finished number makes the
result screen and the archetype page provably equal.

    python build_life_js.py
"""
import io, json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import life_content as lc

OUT = 'C:/Users/Asus/TestMind-site/assets/life.js'


def build():
    data = {}
    for key, d in lc.LIFE.items():
        entry = {'areas': [], 'careers': []}
        for area in ('family', 'school', 'friends'):
            if area not in d:
                continue
            title, sub = lc.AREA_TITLES[area]
            entry['areas'].append({
                'title': title, 'sub': sub,
                'strong': [[t, p] for t, p in d[area]['strong']],
                'weak': [[t, p] for t, p in d[area]['weak']],
            })
        for name, weights, why in d.get('careers', []):
            entry['careers'].append({'name': name, 'pct': lc.pct(key, weights), 'why': why})
        entry['careers'].sort(key=lambda c: -c['pct'])
        data[key] = entry

    js = (u'// GENERATED by tools/build_life_js.py from life_content.py — do not edit.\n'
          u'// Percentages are pre-computed so the result screen and the archetype page\n'
          u'// can never show a different number for the same direction.\n'
          u'var LIFE_LABELS = %s;\nvar LIFE = %s;\n' % (
              json.dumps({'strong': lc.STRONG_LABEL, 'weak': lc.WEAK_LABEL,
                          'careers': lc.CAREER_TITLE, 'disclaimer': lc.DISCLAIMER},
                         ensure_ascii=False, indent=1),
              json.dumps(data, ensure_ascii=False, indent=1, sort_keys=True)))
    io.open(OUT, 'w', encoding='utf-8', newline='').write(js)
    n_lines = sum(len(a['strong']) + len(a['weak'])
                  for e in data.values() for a in e['areas'])
    print('wrote life.js  %d archetypes, %d bullets, %d directions, %d KB'
          % (len(data), n_lines,
             sum(len(e['careers']) for e in data.values()),
             len(js.encode('utf-8')) // 1024))


if __name__ == '__main__':
    build()
