# -*- coding: utf-8 -*-
u"""Russian names for the career taxonomy. TEXT ONLY.

Names and nothing else. There are deliberately no authored per-career
descriptions: the explanation a student reads is GENERATED by the engine from
the signals that actually drove the recommendation, so it cannot drift out of
agreement with the computation the way a hand-written paragraph would.
"""

FAMILIES = {
    'business': u'Бизнес и предпринимательство',
    'cs': u'Компьютерные науки и ИИ',
    'engineering': u'Инженерия и робототехника',
}

CAREERS = {
    'ai_engineer': u'Инженер по ИИ',
    'business_analyst': u'Бизнес-аналитик',
    'civil_engineer': u'Инженер-строитель',
    'cybersecurity': u'Специалист по кибербезопасности',
    'data_scientist': u'Специалист по данным',
    'electrical_engineer': u'Инженер-электрик',
    'entrepreneur': u'Предприниматель',
    'frontend_developer': u'Frontend-разработчик',
    'industrial_engineer': u'Инженер-технолог',
    'marketing_manager': u'Маркетинг-менеджер',
    'mechanical_engineer': u'Инженер-механик',
    'mobile_developer': u'Разработчик мобильных приложений',
    'operations_manager': u'Операционный менеджер',
    'product_manager': u'Продакт-менеджер',
    'robotics_engineer': u'Инженер-робототехник',
    'sales_manager': u'Менеджер по продажам',
    'software_engineer': u'Инженер-программист',
    'systems_analyst': u'Системный аналитик',
    'technician': u'Технический специалист',
}

MAJORS = {
    'major_business_admin': u'Бизнес-администрирование',
    'major_civil_eng': u'Строительная инженерия',
    'major_cs': u'Компьютерный инжиниринг',
    'major_data_science': u'Анализ данных',
    'major_electrical_eng': u'Электроэнергетика',
    'major_info_security': u'Информационная безопасность',
    'major_management': u'Менеджмент',
    'major_marketing': u'Маркетинг',
    'major_mechanical_eng': u'Машиностроение',
    'major_mechatronics': u'Мехатроника и робототехника',
    'major_software_eng': u'Программная инженерия',
}
