# -*- coding: utf-8 -*-
u"""English names for the career taxonomy. TEXT ONLY.

Names and nothing else. There are deliberately no authored per-career
descriptions: the explanation a student reads is GENERATED by the engine from
the signals that actually drove the recommendation, so it cannot drift out of
agreement with the computation the way a hand-written paragraph would.
"""

FAMILIES = {
    'business': u'Business & Entrepreneurship',
    'cs': u'Computer Science & AI',
    'engineering': u'Engineering & Robotics',
}

CAREERS = {
    'ai_engineer': u'AI Engineer',
    'business_analyst': u'Business Analyst',
    'civil_engineer': u'Civil Engineer',
    'cybersecurity': u'Cybersecurity Engineer',
    'data_scientist': u'Data Scientist',
    'electrical_engineer': u'Electrical Engineer',
    'entrepreneur': u'Entrepreneur',
    'frontend_developer': u'Frontend Developer',
    'industrial_engineer': u'Industrial Engineer',
    'marketing_manager': u'Marketing Manager',
    'mechanical_engineer': u'Mechanical Engineer',
    'mobile_developer': u'Mobile Developer',
    'operations_manager': u'Operations Manager',
    'product_manager': u'Product Manager',
    'robotics_engineer': u'Robotics Engineer',
    'sales_manager': u'Sales Manager',
    'software_engineer': u'Software Engineer',
    'systems_analyst': u'Systems Analyst',
    'technician': u'Technician',
}

MAJORS = {
    'major_business_admin': u'Business Administration',
    'major_civil_eng': u'Civil Engineering',
    'major_cs': u'Computer Engineering',
    'major_data_science': u'Data Science',
    'major_electrical_eng': u'Electrical Power Engineering',
    'major_info_security': u'Information Security',
    'major_management': u'Management',
    'major_marketing': u'Marketing',
    'major_mechanical_eng': u'Mechanical Engineering',
    'major_mechatronics': u'Mechatronics and Robotics',
    'major_software_eng': u'Software Engineering',
}
