# -*- coding: utf-8 -*-
u"""Uzbek names for the career taxonomy. TEXT ONLY.

Names and nothing else. There are deliberately no authored per-career
descriptions: the explanation a student reads is GENERATED by the engine from
the signals that actually drove the recommendation, so it cannot drift out of
agreement with the computation the way a hand-written paragraph would.
"""

FAMILIES = {
    'business': u'Biznes va tadbirkorlik',
    'cs': u'Kompyuter fanlari va sunʼiy intellekt',
    'engineering': u'Muhandislik va robototexnika',
}

CAREERS = {
    'ai_engineer': u'Sunʼiy intellekt muhandisi',
    'business_analyst': u'Biznes tahlilchi',
    'civil_engineer': u'Qurilish muhandisi',
    'cybersecurity': u'Kiberxavfsizlik mutaxassisi',
    'data_scientist': u'Maʼlumotlar tahlilchisi',
    'electrical_engineer': u'Elektr muhandisi',
    'entrepreneur': u'Tadbirkor',
    'frontend_developer': u'Frontend dasturchi',
    'industrial_engineer': u'Ishlab chiqarish muhandisi',
    'marketing_manager': u'Marketing menejeri',
    'mechanical_engineer': u'Mashinasozlik muhandisi',
    'mobile_developer': u'Mobil ilova dasturchisi',
    'operations_manager': u'Operatsion menejer',
    'product_manager': u'Mahsulot menejeri',
    'robotics_engineer': u'Robototexnika muhandisi',
    'sales_manager': u'Savdo menejeri',
    'software_engineer': u'Dasturiy taʼminot muhandisi',
    'systems_analyst': u'Tizim tahlilchisi',
    'technician': u'Texnik mutaxassis',
}

MAJORS = {
    'major_business_admin': u'Biznes boshqaruvi',
    'major_civil_eng': u'Qurilish muhandisligi',
    'major_cs': u'Kompyuter injiniringi',
    'major_data_science': u'Maʼlumotlar tahlili',
    'major_electrical_eng': u'Elektroenergetika',
    'major_info_security': u'Axborot xavfsizligi',
    'major_management': u'Menejment',
    'major_marketing': u'Marketing',
    'major_mechanical_eng': u'Mashinasozlik',
    'major_mechatronics': u'Mexatronika va robototexnika',
    'major_software_eng': u'Dasturiy injiniring',
}
